[language-server.ruff]
command = "ruff"
args = ["server"]

[language-server.pyright.config.python.analysis]
typeCheckingMode = "standard"
autoImportCompletions = true

[[language]]
name = "python"
language-servers = ["pyright", "ruff"]

