[language-server.ruff]
command = "ruff"
args = ["server"]

[language-server.harper-ls]
command = "harper-ls"
args = ["--stdio"]

[language-server.pyright.config.python.analysis]
typeCheckingMode = "standard"
autoImportCompletions = true

[language-server.texlab.config.texlab]
build.onSave = true
chktex = { onOpenAndSave = true, onEdit = true }

[[language]]
name = "python"
language-servers = ["pyright", "ruff", "harper-ls"]

[[language]]
name = "latex"
language-servers = ["texlab"]
