# Subliminal Theme
# Author: bmucsanyi <b.h.mucsanyi@gmail.com>
# License: MIT
# Inspired by the Dark Void Helix theme

# UI
"ui.cursor" = { fg = "cursor", modifiers = ["reversed"] }
"ui.cursor.insert" = { fg = "cursor", modifiers = ["reversed"] }
"ui.cursor.select" = { fg = "cursor", modifiers = ["reversed"] }
"ui.cursor.match" = { fg = "search_highlight", modifiers = ["underlined"] }
"ui.cursor.primary" = { fg = "cursor", modifiers = ["reversed"] }
"ui.cursor.primary.normal" = { fg = "cursor", modifiers = ["reversed"] }
"ui.cursor.primary.insert" = { fg = "cursor", modifiers = ["reversed"] }
"ui.cursor.primary.select" = { fg = "cursor", modifiers = ["reversed"] }
"ui.debug.breakpoint" = { fg = "error" }
"ui.debug.active" = { fg = "cursor" }
"ui.gutter" = { }
"ui.gutter.selected" = { fg = "cursor" }
"ui.linenr" = { fg = "line_nr" }
"ui.linenr.selected" = { fg = "cursor" }
"ui.statusline" = { fg = "fg" }
"ui.statusline.inactive" = { fg = "comment" }
"ui.statusline.normal" = { fg = "fg" }
"ui.statusline.insert" = { fg = "bg" }
"ui.statusline.select" = { fg = "bg" }
"ui.popup" = { fg = "fg", bg = "pmenu_bg" }
"ui.window" = { fg = "border" }
"ui.help" = { fg = "fg", bg = "bg" }
"ui.text" = { fg = "fg" }
"ui.text.focus" = { fg = "cursor", bg = "bg", modifiers = ["bold"] }
"ui.text.inactive" = { fg = "comment" }
"ui.virtual.ruler" = { bg = "visual" }
"ui.virtual.whitespace" = { fg = "line_nr" }
"ui.virtual.indent-guide" = { fg = "line_nr" }
"ui.menu" = { fg = "pmenu_fg", bg = "pmenu_bg" }
"ui.menu.selected" = { fg = "bg", bg = "pmenu_sel_bg", modifiers = ["bold"] }
"ui.menu.scroll" = { fg = "pmenu_sel_bg", bg = "pmenu_bg" }
"ui.selection" = { bg = "visual" }
"ui.selection.primary" = { bg = "visual", modifiers = ["bold"] }
"ui.highlight" = { bg = "visual", fg = "fg" }
"ui.cursorline.primary" = { bg = "visual" }
"ui.cursorline.secondary" = { bg = "visual" }
"ui.cursorcolumn.primary" = { bg = "visual" }
"ui.cursorcolumn.secondary" = { bg = "visual" }

# Syntax highlighting
"attribute" = "preprocessor"
"type" = "type"
"type.builtin" = "type"
"constructor" = "func"
"constant" = "constant"
"string" = "string"
"string.regexp" = { fg = "string", modifiers = ["bold"] }
"string.special" = { fg = "string", modifiers = ["bold"] }
"comment" = { fg = "comment", modifiers = ["italic"] }
"variable" = "identifier"
"variable.builtin" = { fg = "identifier", modifiers = ["bold"] }
"variable.parameter" = "identifier"
"variable.other.member" = "identifier"
"label" = "kw"
"punctuation" = "bracket"
"punctuation.delimiter" = "bracket"
"punctuation.bracket" = "bracket"
"punctuation.special" = "bracket"
"keyword" = "kw"
"keyword.control" = { fg = "kw", modifiers = ["bold"] }
"keyword.control.conditional" = { fg = "kw", modifiers = ["bold"] }
"keyword.control.repeat" = { fg = "kw", modifiers = ["bold"] }
"keyword.control.import" = { fg = "kw", modifiers = ["bold"] }
"keyword.control.return" = { fg = "kw", modifiers = ["bold"] }
"keyword.control.exception" = { fg = "kw", modifiers = ["bold"] }
"keyword.operator" = "operator"
"keyword.function" = { fg = "kw", modifiers = ["bold"] }
"keyword.storage" = { fg = "kw", modifiers = ["bold"] }
"keyword.storage.type" = { fg = "kw", modifiers = ["bold"] }
"keyword.storage.modifier" = { fg = "kw", modifiers = ["bold"] }
"operator" = "operator"
"function" = "func"
"function.method" = "func"
"function.special" = "func"
"tag" = "func"
"namespace" = "type"
"special" = { fg = "kw", modifiers = ["bold"] }

# Markup
"markup.heading" = { fg = "kw", modifiers = ["bold"] }
"markup.list" = "kw"
"markup.bold" = { fg = "fg", modifiers = ["bold"] }
"markup.italic" = { fg = "fg", modifiers = ["italic"] }
"markup.link.url" = "string"
"markup.link.text" = "identifier"
"markup.quote" = { fg = "comment", modifiers = ["italic"] }
"markup.raw" = "string"

# Diff
"diff.plus" = "added"
"diff.minus" = "removed"
"diff.delta" = "changed"

# Diagnostics
"diagnostic" = { modifiers = ["underlined"] }
"diagnostic.hint" = { fg = "hint", modifiers = ["underlined"] }
"diagnostic.info" = { fg = "info", modifiers = ["underlined"] }
"diagnostic.warning" = { fg = "warning", modifiers = ["underlined"] }
"diagnostic.error" = { fg = "error", modifiers = ["underlined"] }
"diagnostic.unnecessary" = { modifiers = ["dim"] }
"diagnostic.deprecated" = { modifiers = ["crossed_out"] }

# Elixir-specific (including atoms)
"constant.character.escape" = "string"
"constant.character" = "string"
"symbol" = { fg = "kw", modifiers = ["italic"] }

[palette]
fg = "#c0c0c0"
bg = "#1c1c1c"
cursor = "#1bfd9c"
line_nr = "#585858"
visual = "#303030"
comment = "#585858"
string = "#1ac5b0"
func = "#dbdbdb"
kw = "#1bfd9c"
identifier = "#b1b1b1"
type = "#a1a1a1"
search_highlight = "#1bfd9c"
operator = "#1bfd9c"
bracket = "#e6e6e6"
preprocessor = "#4b8902"
constant = "#b2d8d8"  # "#66b2b2"
added = "#baffc9"
changed = "#ffffba"
removed = "#ffb3ba"
error = "#dea6a0"
warning = "#d6efd8"
hint = "#bedc74"
info = "#7fa1c3"
pmenu_bg = "#1c1c1c"
pmenu_sel_bg = "#1bfd9c"
pmenu_fg = "#c0c0c0"
eob = "#3c3c3c"
border = "#585858"
title = "#bdfe58"
bufferline_selection = "#1bfd9c"
